name: Run script

on:
  schedule:
    - cron: "0 18 * * MON-FRI"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Main script
        run: |
          echo test
